Repository openshift-assisted/assisted-events-scrape, pull requests merged in 2021-11, with the labels that each got.

#1 Add description and env-variables list to the readme file
  README.md
Labels: lgtm

#6 test
  OWNERS_ALIASES
Labels: lgtm, approved

#7 MGMT-7947: Adding Openshift template
  Makefile
  README.md
  events_scrap/events_scrap.py
  openshift/template.yaml
  utils/utils.py
Labels: lgtm, approved

#8 Add build_deploy script for the app-sre jenkins image creation build
  Makefile
  build_deploy.sh
Labels: lgtm, approved

#9 adding execute permission to the build_deploy script
  build_deploy.sh
Labels: approved

#10 fixing image parameter refactor
  build_deploy.sh
Labels: lgtm, approved

#11 exporting ASSISTED_EVENTS_SCRAPE_IMAGE param, the makefile builds the…
  build_deploy.sh
Labels: lgtm, approved

#12 wrong template indentation
  openshift/template.yaml
Labels: lgtm, approved

#13 build image no cache
  Makefile
  build_deploy.sh
  openshift/template.yaml
Labels: approved

#14 Adding entrypoint to the Dockerfile
  Dockerfile
Labels: lgtm, approved

#15 Fix entrypoint of docker container
  Dockerfile
Labels: lgtm, approved

#16 Redirect output to the stdout only by default
  README.md
  assisted-events-scrape/events_scrape/logger.py
Labels: lgtm, approved

#17 fixing a dependency cycle: between logs and events_scrape
  assisted-events-scrape/events_scrape/logger.py
Labels: lgtm, approved

#18 Configuring assisted-service url and remove old misleading environment…
  README.md
  assisted-events-scrape/events_scrape/events_scrape.py
  openshift/template.yaml
Labels: lgtm, approved

#19 get values from dedicated events-scrape secret
  README.md
  openshift/template.yaml
Labels: lgtm, approved

#20 downgrading elasticsearch client. the latest version throwing
  requirements.txt
Labels: lgtm, approved

#21 update setup.py
  setup.py
Labels: lgtm, approved
