Repository openshift-assisted/assisted-events-scrape, pull requests merged in 2022-02, with the labels that each got.

#36 Removing invalid quote
  openshift/template.yaml
Labels: approved

#37 Adding NAMESPACE param definition to the template
  openshift/template.yaml
Labels: approved

#38 Reading Elastic credentials from secret
  openshift/template.yaml
Labels: approved

#39 Adding Elastic credentials for assisted-events-scrape
  openshift/template.yaml
Labels: approved

#40 get namespace from pod metadata
  openshift/template.yaml
Labels: lgtm, approved, needs-ok-to-test

#41 print error info including stack trace
  assisted-events-scrape/events_scrape/events_scrape.py
Labels: approved

#44 Proxy AWS opendistro dashboard directly
  docs/deployment.md
  openshift/template.yaml
Labels: lgtm, approved, ok-to-test
