Repository openshift-assisted/assisted-events-scrape, pull requests merged in 2022-07, with the labels that each got.

#116 remove basic auth on oauth proxy
  openshift/template.yaml
Labels: lgtm, approved, size/S

#117 add infra-env information to events
  assisted-events-scrape/ccx_export/export_to_s3.py
  assisted-events-scrape/config/event_store.py
  assisted-events-scrape/events_scrape/events_scrape.py
  assisted-events-scrape/repositories/__init__.py
  assisted-events-scrape/repositories/cluster_repository.py
  assisted-events-scrape/repositories/event_repository.py
  assisted-events-scrape/tests/integration/fixtures/infra_env-3cef974f-f6fa-4800-bbc8-91519bfe17fe.json
  assisted-events-scrape/tests/integration/test_integration.py
  assisted-events-scrape/tests/unit/test_cluster_events_worker.py
  assisted-events-scrape/tests/unit/test_cluster_repository.py
  assisted-events-scrape/tests/unit/test_events_exporter.py
  assisted-events-scrape/utils/hash.py
  assisted-events-scrape/workers/cluster_events_worker.py
  elasticsearch/templates/default.json
  tools/deploy_manifests.sh
  tools/generate_mockserver_config.py
Labels: lgtm, approved, size/L

#118 bugfix: do not modify cluster event object
  assisted-events-scrape/tests/integration/test_integration.py
  assisted-events-scrape/workers/cluster_events_worker.py
Labels: lgtm, approved, size/S

#120 NO-ISSUE: only execute docker (get_endpoint.sh) for local env
  tools/run_integration_test.sh
Labels: lgtm, approved, size/XS

#119 MGMT-10912 - Remove `user_name` from cluster object
  assisted-events-scrape/storage/cluster_events_storage.py
  assisted-events-scrape/tests/integration/test_integration.py
  elasticsearch/templates/assisted-service-events.json
  requirements.txt
Labels: lgtm, approved, size/S

#121 NO-ISSUE: anonymize user_name for CCX export as well
  assisted-events-scrape/storage/cluster_events_storage.py
  assisted-events-scrape/tests/integration/test_integration.py
  assisted-events-scrape/tests/unit/test_anonymizer.py
  assisted-events-scrape/utils/__init__.py
  assisted-events-scrape/utils/anonymizer.py
  assisted-events-scrape/workers/cluster_events_worker.py
Labels: lgtm, approved, size/L
