Repository openshift-assisted/assisted-events-scrape, pull requests merged in 2022-08, with the labels that each got.

#123 remove UUID5 conversion, as it generates collisions
  assisted-events-scrape/tests/integration/test_integration.py
  assisted-events-scrape/workers/cluster_events_worker.py
Labels: lgtm, approved, size/S

#124 set correct hash for cluster_state_id
  assisted-events-scrape/config/event_store.py
  assisted-events-scrape/storage/cluster_events_storage.py
  assisted-events-scrape/tests/integration/test_integration.py
  assisted-events-scrape/tests/unit/test_cluster_events_worker.py
  assisted-events-scrape/workers/__init__.py
  assisted-events-scrape/workers/cluster_events_worker.py
Labels: lgtm, approved, size/L

#125 add dashboard for events importing metrics
  dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml
Labels: lgtm, approved, size/L

#126 events with same ID should not be replaced
  assisted-events-scrape/storage/elasticsearch_storage.py
Labels: lgtm, approved, size/XS

#128 MGMT-11686: install oc and kubectl from docker image
  Dockerfile.build
Labels: lgtm, approved, size/XS

#127 enable cron suspend
  openshift/template.yaml
Labels: lgtm, approved, size/XS

#129 take kubeconform from docker image instead of curl
  Dockerfile.build
Labels: lgtm, approved, size/XS

#130 add cleanup cron
  openshift/template.yaml
  skipper.env
  tools/delete_from_ccx_s3_bucket.py
Labels: lgtm, approved, size/M

#131 change cleanup command
  assisted-events-scrape/ccx_export/__init__.py
  assisted-events-scrape/ccx_export/delete_from_ccx_s3_bucket.py
  openshift/template.yaml
  setup.py
Labels: lgtm, approved, size/S

#133 force free documents from memory
  assisted-events-scrape/storage/object_storage_writer.py
Labels: lgtm, approved, size/XS

#132 fix date aware and naive comparison
  assisted-events-scrape/events/events_exporter.py
  assisted-events-scrape/storage/offset.py
  assisted-events-scrape/tests/unit/test_offset.py
Labels: lgtm, approved, size/S

#134 reduce flakiness of integration test: wait for minio jobs
  tools/deploy_manifests.sh
Labels: lgtm, approved, size/XS

#135 explicitly call GC
  assisted-events-scrape/storage/object_storage_writer.py
Labels: lgtm, approved, size/XS

#137 add event_id to event payload for export
  assisted-events-scrape/tests/integration/test_integration.py
  assisted-events-scrape/tests/unit/test_cluster_events_worker.py
  assisted-events-scrape/workers/cluster_events_worker.py
Labels: lgtm, approved, size/S

#139 parametrize resource requests and limits
  openshift/template.yaml
Labels: lgtm, approved, size/S

#141 set and fix resource policies for cronjobs
  openshift/template.yaml
Labels: lgtm, approved, size/S

#140 upgrade to ubi 8.6
  Dockerfile
Labels: lgtm, approved, size/XS

#138 add file buffering to reduce memory consumption
  assisted-events-scrape/storage/object_storage_writer.py
  openshift/template.yaml
Labels: lgtm, approved, size/M

#142 use suffixed indices for easier maintenance
  README.md
  assisted-events-scrape/config/elasticsearch.py
  assisted-events-scrape/storage/cluster_events_storage.py
  assisted-events-scrape/tests/integration/test_integration.py
  elasticsearch/templates/assisted-service-events.json
  openshift/template.yaml
  tools/run_integration_test.sh
Labels: lgtm, approved, size/M
